INSERT INTO address_country VALUES
(1058, 'BR', 'Brazil', 'Brasil'),
(132, 'AF', 'Afghanistan', 'Afeganistão'),
(175, 'AL', 'Albania', 'Albânia, Republica da'),
(590, 'DZ', 'Algeria', 'Argélia'),
(6912, 'AS', 'American Samoa', 'Samoa Americana'),
(370, 'AD', 'Andorra', 'Andorra'),
(400, 'AO', 'Angola', 'Angola'),
(418, 'AI', 'Anguilla', 'Anguilla'),
(3596, 'AQ', 'Antarctica', 'Antártida'),
(434, 'AG', 'Antigua and Barbuda', 'Antigua e Barbuda'),
(639, 'AR', 'Argentina', 'Argentina'),
(647, 'AM', 'Armenia', 'Armênia, Republica da'),
(655, 'AW', 'Aruba', 'Aruba'),
(698, 'AU', 'Australia', 'Austrália'),
(728, 'AT', 'Austria', 'Áustria'),
(736, 'AZ', 'Azerbaijan', 'Azerbaijão, Republica do'),
(779, 'BS', 'Bahamas', 'Bahamas, Ilhas'),
(809, 'BH', 'Bahrain', 'Bahrein, Ilhas'),
(817, 'BD', 'Bangladesh', 'Bangladesh'),
(833, 'BB', 'Barbados', 'Barbados'),
(850, 'BY', 'Belarus', 'Belarus, Republica da'),
(876, 'BE', 'Belgium', 'Bélgica'),
(884, 'BZ', 'Belize', 'Belize'),
(2291, 'BJ', 'Benin', 'Benin'),
(906, 'BM', 'Bermuda', 'Bermudas'),
(1198, 'BT', 'Bhutan', 'Butão'),
(973, 'BO', 'Bolivia', 'Bolívia'),
(981, 'BA', 'Bosnia and Herzegowina', 'Bósnia-herzegovina (Republica da)'),
(1015, 'BW', 'Botswana', 'Botsuana'),
(1023, 'BV', 'Bouvet Island', 'Bouvet, Ilha'),
(7820, 'IO', 'British Indian Ocean Territory', 'Território Britânico do Oceano Indico'),
(1082, 'BN', 'Brunei Darussalam', 'Brunei'),
(1112, 'BG', 'Bulgaria', 'Bulgária, Republica da'),
(310, 'BF', 'Burkina Faso', 'Burkina Faso'),
(1155, 'BI', 'Burundi', 'Burundi'),
(1414, 'KH', 'Cambodia', 'Camboja'),
(1457, 'CM', 'Cameroon', 'Camarões'),
(1490, 'CA', 'Canada', 'Canada'),
(1279, 'CV', 'Cape Verde', 'Cabo Verde, Republica de'),
(1376, 'KY', 'Cayman Islands', 'Cayman, Ilhas'),
(6408, 'CF', 'Central African Republic', 'Republica Centro-Africana'),
(7889, 'TD', 'Chad', 'Chade'),
(1589, 'CL', 'Chile', 'Chile'),
(1600, 'CN', 'China', 'China, Republica Popular'),
(5118, 'CX', 'Christmas Island', 'Christmas, Ilha (Navidad)'),
(1651, 'CC', 'Cocos (Keeling) Islands', 'Cocos (Keeling), Ilhas'),
(1694, 'CO', 'Colombia', 'Colômbia'),
(1732, 'KM', 'Comoros', 'Comores, Ilhas'),
(1775, 'CG', 'Congo', 'Congo'),
(8885, 'CD', 'Congo, the Democratic Republic of the', 'Congo, Republica Democrática do'),
(1830, 'CK', 'Cook Islands', 'Cook, Ilhas'),
(1961, 'CR', 'Costa Rica', 'Costa Rica'),
(1937, 'CI', 'Cote d`Ivoire', 'Costa do Marfim'),
(1953, 'HR', 'Croatia (Hrvatska)', 'Croácia (Republica da)'),
(1996, 'CU', 'Cuba', 'Cuba'),
(1635, 'CY', 'Cyprus', 'Chipre'),
(7919, 'CZ', 'Czech Republic', 'Tcheca, Republica'),
(2321, 'DK', 'Denmark', 'Dinamarca'),
(7838, 'DJ', 'Djibouti', 'Djibuti'),
(2356, 'DM', 'Dominica', 'Dominica, Ilha'),
(6475, 'DO', 'Dominican Republic', 'Republica Dominicana'),
(7951, 'TL', 'East Timor', 'Timor Leste'),
(2399, 'EC', 'Ecuador', 'Equador'),
(2402, 'EG', 'Egypt', 'Egito'),
(6874, 'SV', 'El Salvador', 'El Salvador'),
(3310, 'GQ', 'Equatorial Guinea', 'Guine-Equatorial'),
(2437, 'ER', 'Eritrea', 'Eritreia'),
(2518, 'EE', 'Estonia', 'Estônia, Republica da'),
(2534, 'ET', 'Ethiopia', 'Etiópia'),
(2550, 'FK', 'Falkland Islands (Malvinas)', 'Falkland (Ilhas Malvinas)'),
(2593, 'FO', 'Faroe Islands', 'Feroe, Ilhas'),
(8702, 'FJ', 'Fiji', 'Fiji'),
(2712, 'FI', 'Finland', 'Finlândia'),
(2755, 'FR', 'France', 'Franca'),
(3255, 'GF', 'French Guiana', 'Guiana francesa'),
(5991, 'PF', 'French Polynesia', 'Polinésia Francesa'),
(3607, 'TF', 'French Southern Territories', 'Terras Austrais e Antárticas Francesas'),
(2810, 'GA', 'Gabon', 'Gabão'),
(2852, 'GM', 'Gambia', 'Gambia'),
(2917, 'GE', 'Georgia', 'Georgia, Republica da'),
(230, 'DE', 'Germany', 'Alemanha'),
(2895, 'GH', 'Ghana', 'Gana'),
(2933, 'GI', 'Gibraltar', 'Gibraltar'),
(3018, 'GR', 'Greece', 'Grécia'),
(3050, 'GL', 'Greenland', 'Groenlândia'),
(2976, 'GD', 'Grenada', 'Granada'),
(3093, 'GP', 'Guadeloupe', 'Guadalupe'),
(3131, 'GU', 'Guam', 'Guam'),
(3174, 'GT', 'Guatemala', 'Guatemala'),
(3298, 'GN', 'Guinea', 'Guine'),
(3344, 'GW', 'Guinea-Bissau', 'Guine-Bissau'),
(3379, 'GY', 'Guyana', 'Guiana'),
(3417, 'HT', 'Haiti', 'Haiti'),
(3603, 'HM', 'Heard and Mc Donald Islands', 'Ilha Heard e Ilhas McDonald'),
(8486, 'VA', 'Holy See (Vatican City State)', 'Vaticano, Estado da Cidade do'),
(3450, 'HN', 'Honduras', 'Honduras'),
(3514, 'HK', 'Hong Kong', 'Hong Kong'),
(3557, 'HU', 'Hungary', 'Hungria, Republica da'),
(3794, 'IS', 'Iceland', 'Islândia'),
(3611, 'IN', 'India', 'Índia'),
(3654, 'ID', 'Indonesia', 'Indonésia'),
(3727, 'IR', 'Iran (Islamic Republic of)', 'Ira, Republica Islâmica do'),
(3697, 'IQ', 'Iraq', 'Iraque'),
(3751, 'IE', 'Ireland', 'Irlanda'),
(3832, 'IL', 'Israel', 'Israel'),
(3867, 'IT', 'Italy', 'Itália'),
(3913, 'JM', 'Jamaica', 'Jamaica'),
(3999, 'JP', 'Japan', 'Japão'),
(4030, 'JO', 'Jordan', 'Jordânia'),
(1538, 'KZ', 'Kazakhstan', 'Cazaquistão, Republica do'),
(6238, 'KE', 'Kenya', 'Quênia'),
(4111, 'KI', 'Kiribati', 'Kiribati'),
(1872, 'KP', 'Korea, Democratic People`s Republic of', 'Coreia, Republica Popular Democrática da'),
(1902, 'KR', 'Korea, Republic of', 'Coreia, Republica da'),
(1988, 'KW', 'Kuwait', 'Kuwait'),
(6254, 'KG', 'Kyrgyzstan', 'Quirguiz, Republica'),
(4200, 'LA', 'Lao People`s Democratic Republic', 'Laos, Republica Popular Democrática do'),
(4278, 'LV', 'Latvia', 'Letônia, Republica da'),
(4316, 'LB', 'Lebanon', 'Líbano'),
(4260, 'LS', 'Lesotho', 'Lesoto'),
(4340, 'LR', 'Liberia', 'Libéria'),
(4383, 'LY', 'Libyan Arab Jamahiriya', 'Líbia'),
(4405, 'LI', 'Liechtenstein', 'Liechtenstein'),
(4421, 'LT', 'Lithuania', 'Lituânia, Republica da'),
(4456, 'LU', 'Luxembourg', 'Luxemburgo'),
(4472, 'MO', 'Macau', 'Macau'),
(4499, 'MK', 'North Macedonia', 'Macedônia do Norte'),
(4502, 'MG', 'Madagascar', 'Madagascar'),
(4588, 'MW', 'Malawi', 'Malavi'),
(4553, 'MY', 'Malaysia', 'Malásia'),
(4618, 'MV', 'Maldives', 'Maldivas'),
(4642, 'ML', 'Mali', 'Mali'),
(4677, 'MT', 'Malta', 'Malta'),
(4766, 'MH', 'Marshall Islands', 'Marshall, Ilhas'),
(4774, 'MQ', 'Martinique', 'Martinica'),
(4880, 'MR', 'Mauritania', 'Mauritânia'),
(4855, 'MU', 'Mauritius', 'Mauricio'),
(4885, 'YT', 'Mayotte', 'Mayotte (Ilhas Francesas)'),
(4936, 'MX', 'Mexico', 'México'),
(4995, 'FM', 'Micronesia, Federated States of', 'Micronesia'),
(4944, 'MD', 'Moldova, Republic of', 'Moldávia, Republica da'),
(4952, 'MC', 'Monaco', 'Mônaco'),
(4979, 'MN', 'Mongolia', 'Mongólia'),
(5010, 'MS', 'Montserrat', 'Montserrat, Ilhas'),
(4740, 'MA', 'Morocco', 'Marrocos'),
(5053, 'MZ', 'Mozambique', 'Moçambique'),
(930, 'MM', 'Myanmar', 'Mianmar (Birmânia)'),
(5070, 'NA', 'Namibia', 'Namíbia'),
(5088, 'NR', 'Nauru', 'Nauru'),
(5177, 'NP', 'Nepal', 'Nepal'),
(5738, 'NL', 'Netherlands', 'Países Baixos (Holanda)'),
(5428, 'NC', 'New Caledonia', 'Nova Caledonia'),
(5487, 'NZ', 'New Zealand', 'Nova Zelândia'),
(5215, 'NI', 'Nicaragua', 'Nicarágua'),
(5258, 'NE', 'Niger', 'Níger'),
(5282, 'NG', 'Nigeria', 'Nigéria'),
(5312, 'NU', 'Niue', 'Niue, Ilha'),
(5355, 'NF', 'Norfolk Island', 'Norfolk, Ilha'),
(4723, 'MP', 'Northern Mariana Islands', 'Marianas do Norte'),
(5380, 'NO', 'Norway', 'Noruega'),
(5568, 'OM', 'Oman', 'Oma'),
(5762, 'PK', 'Pakistan', 'Paquistão'),
(5754, 'PW', 'Palau', 'Palau'),
(5800, 'PA', 'Panama', 'Panamá'),
(5452, 'PG', 'Papua New Guinea', 'Papua Nova Guine'),
(5860, 'PY', 'Paraguay', 'Paraguai'),
(5894, 'PE', 'Peru', 'Peru'),
(2674, 'PH', 'Philippines', 'Filipinas'),
(5932, 'PN', 'Pitcairn', 'Pitcairn, Ilha'),
(6033, 'PL', 'Poland', 'Polônia, Republica da'),
(6076, 'PT', 'Portugal', 'Portugal'),
(6114, 'PR', 'Puerto Rico', 'Porto Rico'),
(1546, 'QA', 'Qatar', 'Catar'),
(6602, 'RE', 'Reunion', 'Reunião, Ilha'),
(6700, 'RO', 'Romania', 'Romênia'),
(6769, 'RU', 'Russian Federation', 'Rússia, Federação da'),
(6750, 'RW', 'Rwanda', 'Ruanda'),
(6955, 'KN', 'Saint Kitts and Nevis', 'São Cristovão e Neves, Ilhas'),
(7153, 'LC', 'Saint LUCIA', 'Santa Lucia'),
(7056, 'VC', 'Saint Vincent and the Grenadines', 'São Vicente e Granadinas'),
(6904, 'WS', 'Samoa', 'Samoa'),
(6971, 'SM', 'San Marino', 'San Marino'),
(7200, 'ST', 'Sao Tome and Principe', 'São Tome e Príncipe, Ilhas'),
(531, 'SA', 'Saudi Arabia', 'Arábia Saudita'),
(7285, 'SN', 'Senegal', 'Senegal'),
(7315, 'SC', 'Seychelles', 'Seychelles'),
(7358, 'SL', 'Sierra Leone', 'Serra Leoa'),
(7412, 'SG', 'Singapore', 'Cingapura'),
(2470, 'SK', 'Slovakia (Slovak Republic)', 'Eslovaca, Republica'),
(2461, 'SI', 'Slovenia', 'Eslovênia, Republica da'),
(6777, 'SB', 'Solomon Islands', 'Salomão, Ilhas'),
(7480, 'SO', 'Somalia', 'Somalia'),
(7560, 'ZA', 'South Africa', 'África do Sul'),
(2925, 'GS', 'South Georgia and the South Sandwich Islands', 'Ilhas Geórgia do Sul e Sandwich do Sul'),
(2453, 'ES', 'Spain', 'Espanha'),
(7501, 'LK', 'Sri Lanka', 'Sri Lanka'),
(7102, 'SH', 'St. Helena', 'Santa Helena'),
(7005, 'PM', 'St. Pierre and Miquelon', 'São Pedro e Miquelon'),
(7595, 'SD', 'Sudan', 'Sudão'),
(7706, 'SR', 'Suriname', 'Suriname'),
(7552, 'SJ', 'Svalbard and Jan Mayen Islands', 'Svalbard e Jan Mayen'),
(7544, 'SZ', 'Swaziland', 'Eswatini'),
(7641, 'SE', 'Sweden', 'Suécia'),
(7676, 'CH', 'Switzerland', 'Suíça'),
(7447, 'SY', 'Syrian Arab Republic', 'Síria, Republica Árabe da'),
(1619, 'TW', 'Taiwan, Province of China', 'Formosa (Taiwan)'),
(7722, 'TJ', 'Tajikistan', 'Tadjiquistao, Republica do'),
(7803, 'TZ', 'Tanzania, United Republic of', 'Tanzânia, Republica Unida da'),
(7765, 'TH', 'Thailand', 'Tailândia'),
(8001, 'TG', 'Togo', 'Togo'),
(8052, 'TK', 'Tokelau', 'Toquelau, Ilhas'),
(8109, 'TO', 'Tonga', 'Tonga'),
(8150, 'TT', 'Trinidad and Tobago', 'Trinidad e Tobago'),
(8206, 'TN', 'Tunisia', 'Tunísia'),
(8273, 'TR', 'Turkey', 'Turquia'),
(8249, 'TM', 'Turkmenistan', 'Turcomenistão, Republica do'),
(8230, 'TC', 'Turks and Caicos Islands', 'Turcas e Caicos, Ilhas'),
(8281, 'TV', 'Tuvalu', 'Tuvalu'),
(8338, 'UG', 'Uganda', 'Uganda'),
(8311, 'UA', 'Ukraine', 'Ucrânia'),
(2445, 'AE', 'United Arab Emirates', 'Emirados Árabes Unidos'),
(6289, 'GB', 'United Kingdom', 'Reino Unido'),
(2496, 'US', 'United States', 'Estados Unidos'),
(18664, 'UM', 'United States Minor Outlying Islands', 'Ilhas Menores Distantes dos Estados Unidos'),
(8451, 'UY', 'Uruguay', 'Uruguai'),
(8478, 'UZ', 'Uzbekistan', 'Uzbequistão, Republica do'),
(5517, 'VU', 'Vanuatu', 'Vanuatu'),
(8508, 'VE', 'Venezuela', 'Venezuela'),
(8583, 'VN', 'Viet Nam', 'Vietnã'),
(8630, 'VG', 'Virgin Islands (British)', 'Virgens, Ilhas (Britânicas)'),
(8664, 'VI', 'Virgin Islands (U.S.)', 'Virgens, Ilhas (E.U.A.)'),
(8753, 'WF', 'Wallis and Futuna Islands', 'Wallis e Futuna, Ilhas'),
(6858, 'EH', 'Western Sahara', 'Saara Ocidental'),
(3573, 'YE', 'Yemen', 'Iémen'),
(3883, 'YU', 'Yugoslavia', 'Iugoslávia, República Fed. da'),
(8907, 'ZM', 'Zambia', 'Zâmbia'),
(6653, 'ZW', 'Zimbabwe', 'Zimbabue'),
(1504, 'GG', 'Bailiwick of Guernsey', 'Guernsey, Ilha do Canal (Inclui Alderney e Sark)'),
(1508, 'JE', 'Bailiwick of Jersey', 'Jersey, Ilha do Canal'),
(3595, 'IM', 'Isle of Man', 'Man, Ilha de'),
(4985, 'ME', 'Crna Gora (Montenegro)', 'Montenegro'),
(7370, 'RS', 'SÉRVIA', 'Republika Srbija'),
(7600, 'SS', 'Republic of South Sudan', 'Sudao do Sul'),
(8958, NULL, 'Zona del Canal de Panamá', 'Zona do Canal do Panamá'),
(5780, 'PS', 'Dawlat Filasṭīn', 'Palestina'),
(153, 'AX', 'Åland Islands', 'Aland, Ilhas'),
(200, 'CW', 'Curaçao', 'Curaçao'),
(6998, 'SM', 'Saint Martin', 'São Martinho, Ilha de (Parte Holandesa)'),
(990, 'AN', 'Bonaire', 'Bonaire'),
(420, 'AQ', 'Antartica', 'Antartica'),
(3433, 'AU', 'Heard Island and McDonald Islands', 'Ilha Herad e Ilhas Macdonald'),
(6939, 'FR', 'Saint-Barthélemy', 'São Bartolomeu'),
(6980, 'SM', 'Saint Martin', 'São Martinho, Ilha de (Parte Francesa)'),
(7811, 'TF', 'Terres Australes et Antarctiques Françaises', 'Terras Austrais e Antárcticas Francesas');